version: "2"
services:
  nginx:
    container_name: nginx
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    tty: true
    restart: always
    depends_on:
      - front

  front:
    container_name: front
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      PORT: "3000"
      HOST: "0.0.0.0"
    ports:
      - 6006:6006
    expose:
      - 3000
    volumes:
      - ./web:/app
    command: sh -c "npm run dev"
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - back

  back:
    container_name: back
    build:
      context: ./.docker/api
      dockerfile: Dockerfile
    environment:
      # LANG: 'ja_JP.UTF-8'
      # TZ: 'Asia/Tokyo'
      # LOG_CHANNEL: 'stderr'
      # DB_CONNECTION: 'fukuriku'
      # DB_HOST: 'db'
      # DB_PORT: '5432'
      # DB_DATABASE: 'fukuriku'
      # DB_USERNAME: 'fukuriku'
      # DB_PASSWORD: 'password'
      SESSION_DOMAIN: "localhost"
      SANCTUM_STATEFUL_DOMAINS: "localhost"
    volumes:
      - ./api:/app
    expose:
      - 9000
    tty: true
    restart: always
    depends_on:
      - db

  db:
    container_name: db
    image: "postgres:10-alpine"
    restart: always
    environment:
      - POSTGRES_DB=fukuriku
      - POSTGRES_USER=fukuriku
      - POSTGRES_PASSWORD=password
    #   - PGDATA=/var/lib/postgresql/data/pgdata
    # volumes:
    #   - db:/var/lib/postgresql/data
    ports:
      - 5433:5432
  db2:
    container_name: db2
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=fukuriku2
      - POSTGRES_USER=fukuriku2
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
  pgadmin4:
    image: dpage/pgadmin4:4.2
    container_name: pgadmin4
    ports:
      - 5050:80
    volumes:
      - ./docker/pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    depends_on:
      - db
      - db2
    restart: always
volumes:
  db:
  db2:
