version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION_ATS: fukuriku_testing
          - DB_CONNECTION_FUK: ats_testing
      - image: circleci/postgres:10-alpine
    steps:
      - checkout

      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist --working-dir=./api
      - run:
          name: php test
          command: ./api/vendor/bin/phpunit --configuration=./api/phpunit.xml

      - run: echo "Hello World"

