version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:

      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist --working-dir=./api
      - run: apk update
      - run: apk add --no-cache --virtual .php-builds oniguruma-dev postgresql-dev git zip unzip
      - run: docker-php-ext-install mbstring pdo pdo_pgsql
      - run: docker-php-ext-enable mbstring
      - run:
          name: php test
          command: ./api/vendor/bin/phpunit --configuration=./api/phpunit.xml

      - run: echo "Hello World"

